---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monasca-bin
  labels:
    system: openstack
    service: monitoring
    component: configuration

data:
  common.sh: |
{{ .Files.Get "files/common.sh" | indent 4 }}
  common-start: |
{{ .Files.Get "files/common-start" | indent 4 }}
  grafana-start: |
{{ .Files.Get "files/grafana-start" | indent 4 }}



