apiVersion: v1
kind: Service
metadata:
  name: monasca-grafana-helm
  namespace: "{{ .Values.namespace }}"
  labels:
    system: openstack
    service: monitoring
spec:
  selector:
    component: monasca-grafana
  ports:
    - port: {{.Values.monasca.grafana.port.public}}
